[package]
name = "ZDL-Echo"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
eframe = "0.34.3"
crossbeam-channel = "0.5.15"
egui = "0.34.3"
cpal = "0.18.1"
image = "0.25.10"

[profile.dev]
debug = 0 # Skips generating the massive .pdb file on Windows

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3          # Maximum CPU optimization for the DSP math
lto = true             # Link Time Optimization (drastically reduces .exe size and boosts speed)
codegen-units = 1      # Forces the compiler to view the whole program at once to optimize better
panic = "abort"        # Removes crash-unwinding code to save RAM and binary size
strip = true           # Strips all debugging symbols from the final Windows binary

# --- OS-SPECIFIC BUILD CONFIGURATIONS ---

# 1. Windows: Only download winres when building for Windows
[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"

# 2. macOS: Configuration for cargo-bundle
[package.metadata.bundle]
name = "ZDL-Echo"
identifier = "com.zerodaylabs.zdlecho"
icon = ["assets/zdl-echo.ico"]
osx_minimum_system_version = "10.14"

[package.metadata.bundle.osx.info_plist]
# This is the mandatory security prompt macOS shows to the user
NSMicrophoneUsageDescription = "ZDL-Echo requires audio input to capture and decode telecommunications signaling."